baseURL = "http://bigspring.pauluijting.no/"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "pauluijitng.online"
[markup.goldmark.renderer]
unsafe = true
